### PR TITLE
fix: default Country on the InputPhone close #50

### LINKED ISSUE #50: fix: the default Country on the InputPhone
#### Specs
- The default value of the Country should be added by the country set in the phone

### PR DESCRIPTION
**Pull request by devrchancay**
fix: #50 

## Changes proposed in this PR:
-

@nexxtway/react-rainbow

### CODE REVIEW

File: src/components/InputPhone/helpers/getCountryFromValue.ts [hunk 1]
```diff
@@ -1,5 +1,13 @@
+import * as RNLocalize from 'react-native-localize';
 import COUNTRIES from '../countyPickerModal/countries';
 
 export default function getCountryFromValue(isoCode?: string) {
+    if (isoCode === '') {
```
Comment (LeandroTorresSicilia) [inline src/components/InputPhone/helpers/getCountryFromValue.ts:5]: I think here we should first find `COUNTRIES.find(country => country.isoCode === isoCode)` and then if it does not exist then use the ```RNLocalize.getCountry();```
In this way if the user pass an invalid isoCode or if it is not passed at all it will fallback to the device locale

File: src/components/InputPhone/helpers/getCountryFromValue.ts [hunk 2]
```diff
@@ -1,5 +1,13 @@
+import * as RNLocalize from 'react-native-localize';
```
Comment (LeandroTorresSicilia) [inline src/components/InputPhone/helpers/getCountryFromValue.ts:1]: Maybe you can use NativeModules instead of installing a third-party library that applies size overhead
